parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Application\Controller\:
        resource: '../src/Application/Controller'
        tags: ['controller.service_arguments']

    homeboard.connection:
      class: Doctrine\DBAL\Connection
      factory: ['\Doctrine\DBAL\DriverManager', getConnection]
      arguments:
        -
          dbname: '%env(DATABASE_NAME)%'
          user: '%env(DATABASE_USER)%'
          password: '%env(DATABASE_PASSWORD)%'
          host: '%env(DATABASE_HOST)%'
          driver: '%env(DATABASE_DRIVER)%'

    App\DomainModel\Repository\TargetRepository:
      arguments:
        - '@homeboard.connection'
